def get_standard_description(fld_val):
        
    if fld_val==' LACC_AAERIAL_C': return 'AAERIAL_C'
    elif fld_val==' LACC_ATRENCH_C': return 'ATRENCH_C'
    elif fld_val==' LACC_AUG_COPPER': return 'AUG_COPPER'
    elif fld_val==' LACC_AUG_F': return 'AUG_F'
    elif fld_val==' SPST_APOLES ': return 'APOLES'
    elif fld_val==' SPST_SMDF': return 'SMDF'
    elif fld_val=='ABLD_BABLD': return 'BABLD'
    elif fld_val=='INST_ICOMP_PLT': return 'ICOMP_PLT'
    elif fld_val=='LACC_A_DAMAGE': return 'A_DAMAGE'
    elif fld_val=='LACC_AAERIAL_C': return 'AAERIAL_C'
    elif fld_val=='LACC_AAERIAL_F': return 'AAERIAL_F'
    elif fld_val=='LACC_APLOWED_C': return 'APLOWED_C'
    elif fld_val=='LACC_APLOWED_F': return 'APLOWED_F'
    elif fld_val=='LACC_APRESSURE': return 'APRESSURE'
    elif fld_val=='LACC_ATRENCH_C': return 'ATRENCH_C'
    elif fld_val=='LACC_ATRENCH_F': return 'ATRENCH_F'
    elif fld_val=='LACC_AUG_COPPER': return 'AUG_COPPER'
    elif fld_val=='LACC_AUG_F': return 'AUG_F'
    elif fld_val=='LACC_SPROTECTOR': return 'SPROTECTOR'
    elif fld_val=='LACC_TADSL_EQ': return 'TADSL_EQ'
    elif fld_val=='LACC_TFOTS_EQ': return 'TFOTS_EQ'
    elif fld_val=='LACC_THDSL_EQ': return 'THDSL_EQ'
    elif fld_val=='LACC_TPCM_EQ': return 'TPCM_EQ'
    elif fld_val=='LACC_TSRS_EQ': return 'TSRS_EQ'
    elif fld_val=='LNDR_BLNDR': return 'BLNDR'
    elif fld_val=='N/A': return 'N/A'
    elif fld_val=='SPST_ACONDUIT': return 'ACONDUIT'
    elif fld_val=='SPST_AMANHOLES': return 'AMANHOLES'
    elif fld_val=='SPST_APOLES': return 'APOLES'
    elif fld_val=='SPST_APOLES ': return 'APOLES'
    elif fld_val=='SPST_RUNWAY': return 'RUNWAY'
    elif fld_val=='SPST_SCDF': return 'SCDF'
    elif fld_val=='SPST_SMDF': return 'SMDF'
    elif fld_val=='SPST_SMDF ': return 'SMDF'
    elif fld_val=='SRVC_ASERVICE': return 'ASERVICE'
    elif fld_val=='TRNS_A_DAMAGE': return 'A_DAMAGE'
    elif fld_val=='TRNS_AAERIAL_C': return 'AAERIAL_C'
    elif fld_val=='TRNS_AAERIAL_F': return 'AAERIAL_F'
    elif fld_val=='TRNS_APLOWED_C': return 'APLOWED_C'
    elif fld_val=='TRNS_APLOWED_F': return 'APLOWED_F'
    elif fld_val=='TRNS_APRESSURE': return 'APRESSURE'
    elif fld_val=='TRNS_ATRENCH_C': return 'ATRENCH_C'
    elif fld_val=='TRNS_ATRENCH_F': return 'ATRENCH_F'
    elif fld_val=='TRNS_AUG_COPPER': return 'AUG_COPPER'
    elif fld_val=='TRNS_AUG_F': return 'AUG_F'
    elif fld_val=='TRNS_SPROTECTOR': return 'SPROTECTOR'
    elif fld_val=='TRNS_TADSL_EQ': return 'TADSL_EQ'
    elif fld_val=='TRNS_TFOTS_EQ': return 'TFOTS_EQ'
    elif fld_val=='TRNS_THDSL_EQ': return 'THDSL_EQ'
    elif fld_val=='TRNS_TPCM_EQ': return 'TPCM_EQ'
    elif fld_val=='TRNS_TSRS_EQ': return 'TSRS_EQ'

    else: return fld_val