def get_standard_description(fld_val):
        
    # if fld_val==' LACC_AAERIAL_C': return 'AAERIAL_C'
    # elif fld_val==' LACC_ATRENCH_C': return 'ATRENCH_C'
    # elif fld_val==' LACC_AUG_COPPER': return 'AUG_COPPER'
    # elif fld_val==' LACC_AUG_F': return 'AUG_F'
    # elif fld_val==' SPST_APOLES ': return 'APOLES'
    # elif fld_val==' SPST_SMDF': return 'SMDF'
    # elif fld_val=='ABLD_BABLD': return 'BABLD'
    # elif fld_val=='INST_ICOMP_PLT': return 'ICOMP_PLT'
    # elif fld_val=='LACC_A_DAMAGE': return 'A_DAMAGE'
    # elif fld_val=='LACC_AAERIAL_C': return 'AAERIAL_C'
    # elif fld_val=='LACC_AAERIAL_F': return 'AAERIAL_F'
    # elif fld_val=='LACC_APLOWED_C': return 'APLOWED_C'
    # elif fld_val=='LACC_APLOWED_F': return 'APLOWED_F'
    # elif fld_val=='LACC_APRESSURE': return 'APRESSURE'
    # elif fld_val=='LACC_ATRENCH_C': return 'ATRENCH_C'
    # elif fld_val=='LACC_ATRENCH_F': return 'ATRENCH_F'
    # elif fld_val=='LACC_AUG_COPPER': return 'AUG_COPPER'
    # elif fld_val=='LACC_AUG_F': return 'AUG_F'
    # elif fld_val=='LACC_SPROTECTOR': return 'SPROTECTOR'
    # elif fld_val=='LACC_TADSL_EQ': return 'TADSL_EQ'
    # elif fld_val=='LACC_TFOTS_EQ': return 'TFOTS_EQ'
    # elif fld_val=='LACC_THDSL_EQ': return 'THDSL_EQ'
    # elif fld_val=='LACC_TPCM_EQ': return 'TPCM_EQ'
    # elif fld_val=='LACC_TSRS_EQ': return 'TSRS_EQ'
    # elif fld_val=='LNDR_BLNDR': return 'BLNDR'
    # elif fld_val=='N/A': return 'N/A'
    # elif fld_val=='SPST_ACONDUIT': return 'ACONDUIT'
    # elif fld_val=='SPST_AMANHOLES': return 'AMANHOLES'
    # elif fld_val=='SPST_APOLES': return 'APOLES'
    # elif fld_val=='SPST_APOLES ': return 'APOLES'
    # elif fld_val=='SPST_RUNWAY': return 'RUNWAY'
    # elif fld_val=='SPST_SCDF': return 'SCDF'
    # elif fld_val=='SPST_SMDF': return 'SMDF'
    # elif fld_val=='SPST_SMDF ': return 'SMDF'
    # elif fld_val=='SRVC_ASERVICE': return 'ASERVICE'
    # elif fld_val=='TRNS_A_DAMAGE': return 'A_DAMAGE'
    # elif fld_val=='TRNS_AAERIAL_C': return 'AAERIAL_C'
    # elif fld_val=='TRNS_AAERIAL_F': return 'AAERIAL_F'
    # elif fld_val=='TRNS_APLOWED_C': return 'APLOWED_C'
    # elif fld_val=='TRNS_APLOWED_F': return 'APLOWED_F'
    # elif fld_val=='TRNS_APRESSURE': return 'APRESSURE'
    # elif fld_val=='TRNS_ATRENCH_C': return 'ATRENCH_C'
    # elif fld_val=='TRNS_ATRENCH_F': return 'ATRENCH_F'
    # elif fld_val=='TRNS_AUG_COPPER': return 'AUG_COPPER'
    # elif fld_val=='TRNS_AUG_F': return 'AUG_F'
    # elif fld_val=='TRNS_SPROTECTOR': return 'SPROTECTOR'
    # elif fld_val=='TRNS_TADSL_EQ': return 'TADSL_EQ'
    # elif fld_val=='TRNS_TFOTS_EQ': return 'TFOTS_EQ'
    # elif fld_val=='TRNS_THDSL_EQ': return 'THDSL_EQ'
    # elif fld_val=='TRNS_TPCM_EQ': return 'TPCM_EQ'
    # elif fld_val=='TRNS_TSRS_EQ': return 'TSRS_EQ'

    if fld_val=='LACC_3G_HUA_HW': return '3G (HSPA) Hardware - Huawei'
    elif fld_val=='TRNS_3G_HUA_HW': return '3G (HSPA) Hardware - Huawei'
    elif fld_val=='APSW_3G_HUA_SW': return '3G (HSPA) Software - Huawei'
    elif fld_val=='LACC_4G_HUA_HW': return '4G (LTE) Hardware - Huawei'
    elif fld_val=='TRNS_4G_HUA_HW': return '4G (LTE) Hardware - Huawei'
    elif fld_val=='APSW_4G_HUA_SW': return '4G (LTE) Software - Huawei'
    elif fld_val=='LACC_5G_FWA_HW': return '5G_FWA Digital Transmission'
    elif fld_val=='APSW_5G_FWA_SW': return '5G_FWA Application Software'
    elif fld_val=='LACC_5G_SAM_HW': return '4G (LTE)/5G Hardware - Samsung'
    elif fld_val=='TRNS_5G_SAM_HW': return '4G (LTE)/5G Hardware - Samsung'
    elif fld_val=='APSW_5G_SAM_RTU': return '4G (LTE)/5G RTU Licenses - Samsung'
    elif fld_val=='APSW_5G_SAM_SW': return '4G (LTE)/5G Software - Samsung'
    elif fld_val=='LACC_A_DAMAGE': return 'Damages to Customer Property'
    elif fld_val=='TRNS_A_DAMAGE': return 'Damages to Customer Property'
    elif fld_val=='LACC_AAERIAL_C': return 'Aerial Copper'
    elif fld_val=='TRNS_AAERIAL_C': return 'Aerial Copper'
    elif fld_val=='LACC_AAERIAL_F': return 'Aerial Fiber'
    elif fld_val=='TRNS_AAERIAL_F': return 'Aerial Fiber'
    elif fld_val=='SPST_ACONDUIT': return 'Conduit & Underground Duct Structures'
    elif fld_val=='POWR_ACPOWERNEW': return 'AC Power (New)'
    elif fld_val=='SPST_AMANHOLES': return 'Manholes'
    elif fld_val=='LACC_APLOWED_C': return 'Plowed Copper'
    elif fld_val=='TRNS_APLOWED_C': return 'Plowed Copper'
    elif fld_val=='LACC_APLOWED_F': return 'Plowed Fiber'
    elif fld_val=='TRNS_APLOWED_F': return 'Plowed Fiber'
    elif fld_val=='SPST_APOLES': return 'Poles'
    elif fld_val=='LACC_APRESSURE': return 'Pressurization of Cable'
    elif fld_val=='TRNS_APRESSURE': return 'Pressurization of Cable'
    elif fld_val=='APSW_APSW_CS2KL': return 'Communication Server 2000 Software Local Switch'
    elif fld_val=='APSW_APSW_CS2KT': return 'Communication Server 2000 Software Toll Switch'
    elif fld_val=='APSW_APSW_IMS': return 'Multimedia Communication Server Software'
    elif fld_val=='APSW_APSWADMN03': return 'Application Software - Administrative 3 yrs'
    elif fld_val=='APSW_APSWADMN05': return 'Application Software - Administrative 5 yrs'
    elif fld_val=='APSW_APSWADMN10': return 'Application Software - Administrative 10 yrs'
    elif fld_val=='LACC_ATRENCH_C': return 'Trenched Copper'
    elif fld_val=='TRNS_ATRENCH_C': return 'Trenched Copper'
    elif fld_val=='LACC_ATRENCH_F': return 'Trenched Fiber'
    elif fld_val=='TRNS_ATRENCH_F': return 'Trenched Fiber'
    elif fld_val=='LACC_AUG_COPPER': return 'Underground Copper'
    elif fld_val=='TRNS_AUG_COPPER': return 'Underground Copper'
    elif fld_val=='LACC_AUG_F': return 'Underground Fiber'
    elif fld_val=='TRNS_AUG_F': return 'Underground Fiber'
    elif fld_val=='ABLD_B_CPNT1001': return 'Building -Components (1001)'
    elif fld_val=='FBLD_B_CPNT1001': return 'Building -Components (1001)'
    elif fld_val=='ABLD_B_CPNT1005': return 'BUILDING COMPONENTS (1005)'
    elif fld_val=='FBLD_BFBLD': return 'Facility Buildings & Structures'
    elif fld_val=='LAND_BLAND': return 'Land'
    elif fld_val=='LAND_BLAND': return 'Land'
    elif fld_val=='SWTC_BLG': return 'Broadband Line Gateway'
    elif fld_val=='LNDR_BLNDR': return 'Land Rights'
    elif fld_val=='LSHD_BLSHD': return 'Leasehold Improvements'
    elif fld_val=='SPST_BTOWERS': return 'Towers/Monopoles'
    elif fld_val=='SWTC_C20AS_TOLL': return 'Ribbon C20 Toll Switch'
    elif fld_val=='LACC_CACCMAX': return 'NGDLC - Access Max'
    elif fld_val=='SWTC_CACCMAX': return 'NGDLC - Access Max'
    elif fld_val=='TRNS_CACCMAX': return 'NGDLC - Access Max'
    elif fld_val=='LACC_CDMS1U': return 'DMS 1U'
    elif fld_val=='TRNS_CDMS1U': return 'DMS 1U'
    elif fld_val=='COMP_COMP_IMS': return 'Computer Equipment IMS'
    elif fld_val=='SWTC_COMP_IMS': return 'Multimedia Communication Server Hardware'
    elif fld_val=='COMP_COMP_NTWK': return 'OSS & Specialized Ntwk Functionality'
    elif fld_val=='COMP_COMP_PRES': return 'Presentation Equipment'
    elif fld_val=='SRVC_COPPERSERV': return 'Outside Service Wire - Copper'
    elif fld_val=='SWTC_CORE_3G_HW': return 'Core 3G (Circuit Switch) Hardware'
    elif fld_val=='APSW_CORE_3G_SW': return 'Core 3G (Circuit Switch) Software'
    elif fld_val=='SWTC_CORE_5G_HW': return 'Core (4G, 5G) Hardware'
    elif fld_val=='APSW_CORE_5G_SW': return 'Core (4G, 5G) Software'
    elif fld_val=='TERM_CPE_OTHER': return 'CPE - Other'
    elif fld_val=='LACC_CRCU': return 'RCU'
    elif fld_val=='TRNS_CRCU': return 'RCU'
    elif fld_val=='SWTC_CS2K_LOCL': return 'Communication Server 2000 Hardware Local Switch'
    elif fld_val=='POWR_DCPOWER': return 'DC Power'
    elif fld_val=='LACC_DCUST_EQ': return 'Customer Equipment'
    elif fld_val=='TRNS_DCUST_EQ': return 'Customer Equipment'
    elif fld_val=='LACC_DDATA-SET': return 'Dataset Unit'
    elif fld_val=='TRNS_DDATA-SET': return 'Dataset Unit'
    elif fld_val=='LACC_DIMUX_EQ': return 'Intelligent MUX Equipment'
    elif fld_val=='TRNS_DIMUX_EQ': return 'Intelligent MUX Equipment'
    elif fld_val=='APSW_DIVAPSW': return 'Application Software - DIV'
    elif fld_val=='COMP_DIVCOMP': return 'DIV - General Purpose Computers'
    elif fld_val=='TRNS_DIVHEADEND': return 'DIV - Head End Equipment'
    elif fld_val=='TERM_DIVTERM': return 'Customer Premise Equipment'
    elif fld_val=='LACC_DIVVID1001': return 'DIV - Video (1001)'
    elif fld_val=='TRNS_DIVVID1001': return 'DIV - Video (1001)'
    elif fld_val=='LACC_DLAN-WAN': return 'LAN/WAN Equipment (Incl IP Routers & Switches)'
    elif fld_val=='TRNS_DLAN-WAN': return 'LAN/WAN Equipment (Incl IP Routers & Switches)'
    elif fld_val=='TERM_DVIDEO': return 'Video (Terminal)'
    elif fld_val=='APSW_DW_APSW10': return 'DW - Application Software - Administrative 10 YR L'
    elif fld_val=='APSW_DW_APSW3': return 'DW - Application Software - Administrative 3 YR Li'
    elif fld_val=='APSW_DW_APSW5': return 'DW - Application Software - Administrative 5 YR Li'
    elif fld_val=='ARTW_DW_ARTWORK': return 'DW - Corporate Artwork'
    elif fld_val=='SPST_DW_BILLBRD': return 'DW - Digital Out of Home - Billboards'
    elif fld_val=='LNDR_DW_BILLRTS': return 'DW - Digital Out of Home - Contractual rights'
    elif fld_val=='COMP_DW_COMPGP': return 'DW - General Purpose Computers'
    elif fld_val=='COMP_DW_COMPPC': return 'DW - Personal Computers'
    elif fld_val=='FBLD_EXBLD': return 'EXCHANGE & SWITCHING BUILDING Type E'
    elif fld_val=='FSVC_FIBRESERV': return 'Outside Service Wire - Fibre'
    elif fld_val=='ARTW_GARTWORK': return 'Artwork'
    elif fld_val=='FURN_GFURN_FOOD': return 'Furniture Restaurant'
    elif fld_val=='FURN_GFURN_FOOD': return 'Furniture Restaurant'
    elif fld_val=='FURN_GFURN_H&S': return 'Furniture-Health & Safety'
    elif fld_val=='FURN_GFURN_H&S': return 'Furniture - Health & Safety'
    elif fld_val=='FURN_GFURN_MAIN': return 'Furniture - Maintenance'
    elif fld_val=='FURN_GFURN_OFC': return 'Furniture-Office'
    elif fld_val=='FURN_GFURN_OFC': return 'Furniture - Office'
    elif fld_val=='MEOE_GMOE_CASHC': return 'Mechanical Office Equip - Cash Collection'
    elif fld_val=='MEOE_GMOE_GP': return 'Mechanical Office Equip - General Purpose'
    elif fld_val=='MEOE_GMOE_MAILR': return 'Mechanical Office Equip - Mailroom'
    elif fld_val=='TERM_GTERM': return 'Terminals'
    elif fld_val=='TEST_GTEST': return 'Network Tools & Test Equipment > $1500'
    elif fld_val=='TOOL_GTOOL': return 'Non-Netowkr Tools & Test Equipment > $1500'
    elif fld_val=='AVEH_GVECH_AUX': return 'Vehicles - Related Tools'
    elif fld_val=='CVEH_GVECH_CONS': return 'Vehicles - Construction'
    elif fld_val=='VMNT_GVECH_MNT': return 'Vehicles - Mounted Equipment'
    elif fld_val=='SVEH_GVECH_SER': return 'Vehicles - Service'
    elif fld_val=='SPST_HDTOWERS': return 'Heavy Duty Towers'
    elif fld_val=='TERM_HSMODEM': return 'CPE High Speed Modems'
    elif fld_val=='COMP_ICOMP_GP': return 'Computers General Purpose'
    elif fld_val=='COMP_ICOMP_PC': return 'Personal Computers & Sound/Optical Technologies'
    elif fld_val=='COMP_ICOMP_PC': return 'Computers Personal'
    elif fld_val=='INST_ICOMP_PLT': return 'Monitoring Network Elements (RTU"S,etc.)'
    elif fld_val=='COMP_ICOMP_WIFI': return 'WIFI Cables,Routers,Ports,Antennas,Power,Etc.'
    elif fld_val=='SPST_LDTOWERS': return 'Light Duty Towers'
    elif fld_val=='SPST_LIGHTPOLES': return 'Light Poles'
    elif fld_val=='LACC_LTE_TDD_HW': return '4G (LTE-TDD) Hardware - Fusion'
    elif fld_val=='APSW_LTE_TDD_SW': return '4G (LTE-TDD) Software - Fusion'
    elif fld_val=='LACC_MCS': return 'Multipoint Communication Service'
    elif fld_val=='TRNS_MCS': return 'Multipoint Communication Service'
    elif fld_val=='SPST_MDTOWERS': return 'Medium Duty Towers'
    elif fld_val=='LACC_OLT_EQ': return 'OLT Equipment'
    elif fld_val=='TERM_ONT_ONU_EQ': return 'ONT & ONU Equipment'
    elif fld_val=='POWR_PAC_SPL': return 'AC Speical Arrangements'
    elif fld_val=='POWR_PBATT-48': return 'Batteries -48 Volt (FLOODED)'
    elif fld_val=='POWR_PBATT+24': return 'Batteries +24 Volt (FLOODED)'
    elif fld_val=='POWR_PDCPLT-48': return 'DC Plant -48 Volt'
    elif fld_val=='POWR_PDCPLT+24': return 'DC Plant +24 Volt'
    elif fld_val=='POWR_PRECT-48': return 'Rectifiers -48 Volt'
    elif fld_val=='POWR_PRECT+24': return 'Rectifiers +24 Volt'
    elif fld_val=='TERM_PUBLICACC': return 'Public Access Terminals (Payphones)'
    elif fld_val=='APSW_SAPSW_ALMS': return 'OSS & Specialized Ntwk Functionality'
    elif fld_val=='APSW_SAPSW_LOCL': return 'Application Software Switch - Local'
    elif fld_val=='APSW_SAPSW_STP': return 'Application Software Switch - STP'
    elif fld_val=='APSW_SAPSW_TOLL': return 'Application Software Switch - Toll'
    elif fld_val=='LACC_SCCI': return 'Circuit Conditioning'
    elif fld_val=='TRNS_SCCI': return 'Circuit Conditioning'
    elif fld_val=='SWTC_SDMS_RLM': return 'DMS Remote Line Module'
    elif fld_val=='SWTC_SDMS_RLMC': return 'DMS Remote Line Concentrating Module'
    elif fld_val=='SWTC_SDMS_RSC': return 'DMS Remote Switching Center'
    elif fld_val=='SWTC_SDMS_SRSC': return 'DMS Sonet Remote Switching Center'
    elif fld_val=='SWTC_SDMS100HOS': return 'DMS 100 Host'
    elif fld_val=='SWTC_SDMSSTP': return 'DMS STP Switch'
    elif fld_val=='FBLD_SEBLD': return 'Small Equipment Building'
    elif fld_val=='SPST_SMDF': return 'Main Distributing Frame'
    elif fld_val=='INTG_SPECTRUM': return 'WIRELESS SPECTRUM'
    elif fld_val=='LACC_SPROTECTOR': return 'Protectors'
    elif fld_val=='TRNS_SPROTECTOR': return 'Protectors'
    elif fld_val=='APSW_ST_APSW10': return 'ST - Software - 10 Year Life'
    elif fld_val=='APSW_ST_APSW3': return 'ST - Software - 3 Year Life'
    elif fld_val=='APSW_ST_APSW5': return 'ST - Software - 5 Year Life'
    elif fld_val=='LSHD_ST_BLSHD': return 'ST - Leasehold Improvements'
    elif fld_val=='COMP_ST_COMPGP': return 'ST - General Purpose Computer'
    elif fld_val=='COMP_ST_COMPPC': return 'ST - Personal Computers'
    elif fld_val=='TERM_ST_CPE3': return 'ST - Customer Premise Equipment - 3 Year Life'
    elif fld_val=='TERM_ST_CPE5': return 'ST - Customer Premise Equipment - 5 Year Life'
    elif fld_val=='COMP_ST_STATHW': return 'ST - Central Station Hardware'
    elif fld_val=='SPST_STEALTH_P': return 'Stealth Poles'
    elif fld_val=='LACC_TADSL_EQ': return 'ADSL Equipment'
    elif fld_val=='TRNS_TADSL_EQ': return 'ADSL Equipment'
    elif fld_val=='LACC_TCH_UNIT': return 'Channel Unit'
    elif fld_val=='TRNS_TCH_UNIT': return 'Channel Unit'
    elif fld_val=='COMP_TEL_CLD_HW': return 'Telco Cloud Hardware'
    elif fld_val=='APSW_TEL_CLD_SW': return 'Telco Cloud Software'
    elif fld_val=='LACC_TFOTS_EQ': return 'FOTS Equip (IE Sonet & Optical Digital Multiplex)'
    elif fld_val=='TRNS_TFOTS_EQ': return 'FOTS Equip (Ie. Sonet & Optical Digital Multiplex)'
    elif fld_val=='LACC_THDSL_EQ': return 'HDSL Equipment'
    elif fld_val=='TRNS_THDSL_EQ': return 'HDSL Equipment'
    elif fld_val=='LACC_TM_RDO': return 'Microwave Radio'
    elif fld_val=='TRNS_TM_RDO': return 'Microwave Radio'
    elif fld_val=='LACC_TPCM_EQ': return 'PCM Equipment'
    elif fld_val=='TRNS_TPCM_EQ': return 'PCM Equipment'
    elif fld_val=='LACC_TSATT_EQ': return 'Satellite - Broadcast Services, DIV (MAX), Etc.'
    elif fld_val=='TRNS_TSATT_EQ': return 'Satellite - Broadcast Services, Max, Etc.'
    elif fld_val=='TERM_VOIP_TERM': return 'VOIP Terminals'
    elif fld_val=='POWR_VRLA -48': return 'VRLA Batteries -48 VOLTS (VALVE REGULATED)'
    elif fld_val=='POWR_VRLA +24': return 'VRLA Batteries +24 VOLTS (VALVE REGULATED)'
    elif fld_val=='ABLD_WGBLD': return 'Warehouses & Garages Type WG Buildings'
    elif fld_val=='APSW_WIFI_APSW': return 'WIFI Application Software'
    elif fld_val=='LACC_WIFI_EQUIP': return 'WIFI Transmission Equipment'
    elif fld_val=='SPST_WPTOWERS': return 'Wooden Pole-Towers'

    else: return fld_val